### ISSUE TITLE
URL for iris dataset changed (again)

### ISSUE THREAD

**Issue by sthagen** [rkneusel9/PracticalDeepLearningPython#3]
The URL given as update in the [README.md line 18 on the iris dataset](https://github.com/rkneusel9/PracticalDeepLearningPython/blob/main/README.md?plain=1#L18) would profit from changing to <https://archive.ics.uci.edu/dataset/53/iris/>:

```diff
diff old/README.md new/README.md
18c18
<                 https://archive.ics.uci.edu/ml/machine-learning-databases/iris/
---
>                 https://archive.ics.uci.edu/dataset/53/iris/
```

The one currently stated in the README.md yields a [NOT FOUND](https://archive.ics.uci.edu/ml/machine-learning-databases/iris/).

Thanks for sharing through providing these resources (repositories), much appreciated.

All the best,
Stefan

**Comment by rkneusel9** [comment]
Thanks for catching that.  I wish they would just leave things as they are, but, change is inevitable.  I corrected the Iris URL and the Breast Cancer URL from page 86.

**Comment by sthagen** [comment]
Thanks a lot for the fast reaction and complete fix. Much appreciated.
